name: pegue_e_monte
description: Sistema de gestão de kits para aluguel
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Locale pt-BR
  flutter_localizations:
    sdk: flutter

  # Firebase (opcional no runtime atual)
  firebase_core: ^3.15.2
  cloud_firestore: ^5.5.0

  # Gerenciamento de estado
  provider: ^6.1.2

  # Utilidades
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.3.0
  firebase_auth: ^5.7.0

# ... (mantenha o início igual)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  fake_cloud_firestore: ^3.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png