name: pegue_e_monte
description: Sistema de gestÃ£o de kits para aluguel
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  cloud_firestore: ^5.5.0

  provider: ^6.1.2
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
